version: '3.9'

services:
  flask:
    build: ./app
    container_name: flask_app
    restart: always
    depends_on:
      - redis
      - mongo

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - flask

  redis:
    image: redis:alpine
    container_name: redis_service
    restart: always

  mongo:
    image: mongo:latest
    container_name: mongo_service
    restart: always
    ports:
      - "27017:27017"
